"""Add role for user

Revision ID: d7138e8718e5
Revises: c9cf2c4e83c2
Create Date: 2025-04-05 19:49:00.951429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = "d7138e8718e5"
down_revision: Union[str, None] = "c9cf2c4e83c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = ENUM("USER", "ADMIN", name="userrole", create_type=True)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind())

    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="userrole"),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")

    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
